namespace EasyCrud.Models
{
    public interface IModel<TIndexType>
    {
        bool KeyIsAutogenerated();
        TIndexType GetKey();
        void SetKey(TIndexType value);
        bool KeyEqual(TIndexType value);
        TIndexType GetInvalidKey();
        bool ContentsEqual(IModel<TIndexType> input);
    }
}
