using EasyCrud.Models;
using Microsoft.WindowsAzure.Storage.Table;

namespace EasyCrud.AzureTables.Models
{
    public abstract class ApiTableEntity : TableEntity, IModel<ApiTableEntityKey>
    {
        public bool KeyIsAutogenerated()
        {
            return false;
        }

        public ApiTableEntityKey GetKey()
        {
            var output = new ApiTableEntityKey
            {
                PartitionKey = PartitionKey,
                RowKey = RowKey
            };
            return output;
        }

        public void SetKey(ApiTableEntityKey value)
        {
            PartitionKey = value.PartitionKey;
            RowKey = value.RowKey;
        }

        public bool KeyEqual(ApiTableEntityKey value)
        {
            if(PartitionKey != value.PartitionKey)
            {
                return false;
            }
            if (RowKey != value.RowKey)
            {
                return false;
            }

            return true;
        }

        public ApiTableEntityKey GetInvalidKey()
        {
            return new ApiTableEntityKey();
        }

        public abstract bool ContentsEqual(IModel<ApiTableEntityKey> input);
    }
}
